typography_spectrum: 0.24632000899873674
color:
  brandStrength: 0.11086506117135286
  lightness: 0.7852668040432036
  saturation: 0.32349771866574883
  rhythmicContrast: 0.6745322395581752
  brandColors:
    - '#5A1F00'
    - '#D1570D'
    - '#FDE792'
    - '#477725'
    - '#A9CC66'
layout_spectrum: 0.6866984153166413
author:
  name: Richard Bennett
  email: bennettr63@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/68ef2078-ae18-4355-bc74-ddac61dbea36.exe
name: 'COCEGSA (Criadero Ovino-Caprino El Gaital, S.A.)'
navigation:
  - name: AGOVICA
    url: 'http://www.agovica.com'
    type: external
title: Genética ovina y caprina de primera
